services:
  - type: web
    name: marc
    env: docker
    plan: free
    autoDeploy: true
    region: singapore
    healthCheckPath: /
    # rootDir: MARC

    # Environment variables for database connection (Railway MySQL)
    envVars:
      - key: DB_HOST
        value: "mysql.railway.internal"
      - key: DB_NAME
        value: "railway"                 
      - key: DB_USERNAME
        value: "root"                    
      - key: DB_PASSWORD
        value: "AzCCVTsWzzmokjxzvLEYIGTsFsJYyrdp"
